[package]
name = "kornia-tracking"
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
include.workspace = true
license.workspace = true
license-file.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
glam = "0.30.0"
image = "0.25.0"
imageproc = "0.25.0"
rayon = "1.10"
