[package]
name = "kornia-tracking"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
kornia-image = { workspace = true }
glam = "0.30.0"
kornia-imgproc = { workspace = true }
imageproc = "0.25.0"
log = "0.4.22"
rayon = "1.10"
